import {
  corollaDimensionsM,
  corollaGeometryBuilderConfig,
  corollaGeometryMm,
  corollaSceneMm,
  mmToM,
  sourceDerived,
  sourceSpecsMm,
  tire20555R16,
  xAnchorsMm,
  zAnchorsMm,
} from "./source-metrics";

export {
  corollaGeometryBuilderConfig,
  corollaGeometryMm,
  corollaSceneMm,
  mmToM,
  sourceDerived,
  sourceSpecsMm,
  tire20555R16,
  xAnchorsMm,
  zAnchorsMm,
} from "./source-metrics";

export const corollaBlockoutConfig = {
  dimensionsM: corollaDimensionsM,
  materials: {
    body: {
      color: "#8b949c",
      roughness: 0.34,
      metalness: 0.18,
    },
    glass: {
      color: "#7f9db3",
      opacity: 0.65,
      transparent: true,
    },
    tire: {
      color: "#111111",
      roughness: 0.62,
    },
    rim: {
      color: "#cbd5e1",
      metalness: 0.82,
      roughness: 0.16,
    },
    sportRim: {
      color: "#e5e7eb",
      metalness: 0.82,
      roughness: 0.16,
    },
    wheelCenter: {
      color: "#f8fafc",
      metalness: 0.92,
      roughness: 0.14,
    },
    wheelSpoke: {
      color: "#94a3b8",
      metalness: 0.72,
      roughness: 0.2,
    },
    sportWheelSpoke: {
      color: "#f8fafc",
      metalness: 0.72,
      roughness: 0.2,
    },
    wheelWell: {
      color: "#141414",
      roughness: 0.72,
      metalness: 0.02,
    },
    interiorFabricDark: {
      color: "#1f2329",
      roughness: 0.78,
      metalness: 0.02,
    },
    interiorPlasticDark: {
      color: "#171a20",
      roughness: 0.64,
      metalness: 0.04,
    },
    interiorAccent: {
      color: "#303741",
      roughness: 0.48,
      metalness: 0.12,
    },
    chrome: {
      color: "#d7dde3",
      metalness: 0.86,
      roughness: 0.18,
    },
  },
  geometryMm: corollaGeometryMm,
  sceneMm: corollaSceneMm,
  geometryBuilderConfig: corollaGeometryBuilderConfig,
} as const;

export const corollaVisualSource = {
  groundClearance: mmToM(sourceSpecsMm.groundClearanceNominal),
  cabinLengthRatio: 0.62,
  frontLightHeight: 0.58,
  rearLightHeight: 0.68,
  bodyTaper: 0.34,
  roofCurve: 1.08,
} as const;

export const corollaSchemaCore = {
  metadata: {
    id: "corollaSedan",
    make: "Toyota",
    model: "Corolla",
    year: 2016,
    generation: "E170/E180",
    bodyStyle: "4-door compact sedan",
    market: "global",
    drivetrain: "FWD",
    seatingCapacity: 5,
    sourceFile: "toyota-corolla-2016-3d-design-system.ts",
    sourceNote: "Legacy parametric design reference, not an official CAD scan.",
    designIntent:
      "Clean compact sedan with horizontal visual language, angular front lamps, thin upper grille, large lower intake, practical trunk volume, and moderate urban ride height.",
  },
  dimensions: {
    unit: "meters",
    sourceUnit: "millimeters",
    overallLength: mmToM(sourceSpecsMm.length),
    width: mmToM(sourceSpecsMm.widthNoMirrors),
    visualHeight: mmToM(sourceSpecsMm.height),
    wheelbase: mmToM(sourceSpecsMm.wheelbase),
    frontOverhang: mmToM(sourceDerived.frontOverhang),
    rearOverhang: mmToM(sourceDerived.rearOverhang),
    groundClearance: mmToM(sourceSpecsMm.groundClearanceNominal),
    groundClearanceRange: [mmToM(sourceSpecsMm.groundClearanceMin), mmToM(sourceSpecsMm.groundClearanceMax)],
    cabinLengthRatio: 0.62,
    sourceMm: sourceSpecsMm,
    derivedRatios: {
      lengthToWidth: sourceDerived.lengthToWidthRatio,
      lengthToHeight: sourceDerived.lengthToHeightRatio,
      wheelbaseToLength: sourceDerived.wheelbaseToLengthRatio,
    },
    capacities: {
      trunkFt3: 13.0,
      fuelTankGal: 13.2,
      passengerVolumeFt3: 97.5,
      epaInteriorVolumeFt3Approx: 110.5,
    },
    mass: {
      curbWeightLbTypical: 2855,
      curbWeightKgTypical: 1295.0,
    },
  },
  coordinateSystem: {
    origin: "vehicle-center-on-ground-plane",
    xAxis: "front-to-rear",
    yAxis: "vertical",
    zAxis: "driver-to-passenger-width",
    frontDirection: "negative-x",
    rearDirection: "positive-x",
    scale: 1,
    sourceCoordinateSystem: {
      unit: "millimeters",
      origin: "center of front axle at ground-projected centerline",
      xAxis: "positive from front axle toward rear axle",
      yAxis: "positive to vehicle right side",
      zAxis: "positive upward from ground plane",
    },
    xAnchorsMm,
    zAnchorsMm,
  },
  wheelGeometry: {
    radius: mmToM(tire20555R16.radiusMm),
    width: mmToM(tire20555R16.tireWidthMm),
    archRadiusMultiplier: 1.52,
    lateralOffsetMultiplier: 1.16,
    rimRadiusMultiplier: 0.72,
    defaultSpokes: 7,
    sportSpokes: 10,
    axleGeometryMm: {
      frontAxleX: xAnchorsMm.frontAxle,
      rearAxleX: xAnchorsMm.rearAxle,
      frontWheelCenterLeft: { x: xAnchorsMm.frontAxle, y: -sourceDerived.halfFrontTrack, z: zAnchorsMm.wheelCenter },
      frontWheelCenterRight: { x: xAnchorsMm.frontAxle, y: sourceDerived.halfFrontTrack, z: zAnchorsMm.wheelCenter },
      rearWheelCenterLeft: { x: xAnchorsMm.rearAxle, y: -sourceDerived.halfRearTrack, z: zAnchorsMm.wheelCenter },
      rearWheelCenterRight: { x: xAnchorsMm.rearAxle, y: sourceDerived.halfRearTrack, z: zAnchorsMm.wheelCenter },
      wheelInsetMm: 22,
      wheelArchGapTopMm: 65,
      wheelArchGapFrontRearMm: 55,
      visualCamberDeg: -0.25,
    },
    tireOptions: {
      tire19565R15: {
        label: "P195/65R15",
        rimDiameterIn: 15,
        tireWidthMm: 195,
        aspectRatio: 0.65,
      },
      tire20555R16,
      tire21545R17: {
        label: "P215/45R17",
        rimDiameterIn: 17,
        tireWidthMm: 215,
        aspectRatio: 0.45,
      },
    },
    archGeometryMm: {
      front: {
        centerX: xAnchorsMm.frontAxle,
        centerZ: zAnchorsMm.wheelCenter,
        radiusMm: 395,
        lipThicknessMm: 28,
        flareOutwardMm: 16,
        archStartAngleDeg: 204,
        archEndAngleDeg: -24,
        upperFlattening: 0.07,
      },
      rear: {
        centerX: xAnchorsMm.rearAxle,
        centerZ: zAnchorsMm.wheelCenter,
        radiusMm: 395,
        lipThicknessMm: 28,
        flareOutwardMm: 14,
        archStartAngleDeg: 205,
        archEndAngleDeg: -25,
        upperFlattening: 0.06,
      },
    },
  },
} as const;


export const corollaSchemaShape = {
  bodyVolumes: {
    sourceMassing: {
      type: "three_box_compact_sedan",
      volumeRatiosByLength: {
        frontOverhang: Math.abs(xAnchorsMm.frontBumper) / sourceSpecsMm.length,
        hoodAndCowl: 0.27,
        cabin: 0.46,
        trunk: 0.23,
        rearOverhang: (xAnchorsMm.rearBumper - xAnchorsMm.rearAxle) / sourceSpecsMm.length,
      },
      hood: {
        xStart: xAnchorsMm.frontBumper + 120,
        xEnd: xAnchorsMm.firewallApprox + 130,
        frontZ: zAnchorsMm.hoodFront,
        rearZ: zAnchorsMm.hoodRear - 20,
        slopeDegApprox: 5.2,
        centerCrownMm: 8,
        sideFalloffMm: 18,
        leadingEdgeRoundnessMm: 45,
        rearPanelGapMm: 4,
      },
      cabin: {
        xStart: xAnchorsMm.aPillarBase,
        xEnd: 2550,
        maxHeightZ: 1375,
        roofApexX: 1480,
        roofCrownMm: 20,
        windshieldAngleFromVerticalDeg: 34,
        rearGlassAngleFromVerticalDeg: 38,
        sideGlassInsetMm: 42,
        roofRailRadiusMm: 95,
      },
      trunk: {
        xStart: 2550,
        xEnd: xAnchorsMm.rearBumper - 80,
        deckZ: zAnchorsMm.trunkDeck - 45,
        deckSlopeDeg: -1.4,
        lidCrownMm: 10,
        rearEdgeDropMm: 105,
        trunkSeamGapMm: 4,
      },
      lowerBody: {
        rockerZ: zAnchorsMm.rockerMid,
        rockerDepthMm: 35,
        rockerInsetMm: 22,
        lowerDoorTuckMm: 35,
        underbodyHiddenZ: 170,
      },
    },
    mainBody: {
      center: [0, -0.02, 0],
      lengthRatio: 0.98,
      heightRatio: 0.92,
      widthRatio: 2.02,
      cornerRadius: 0.19,
    },
    frontMass: {
      axlePositionMultiplier: 0.65,
      centerY: 0.12,
      lengthRatio: 0.32,
      heightRatio: 0.58,
      widthRatio: 1.92,
      cornerRadius: 0.15,
    },
    rearMass: {
      axlePositionMultiplier: 0.72,
      centerY: 0.08,
      lengthRatio: 0.26,
      heightRatio: 0.48,
      widthRatio: 1.88,
      cornerRadius: 0.13,
    },
    lowerTrim: {
      yRatio: -0.74,
      lengthRatio: 0.94,
      height: 0.13,
      depth: 0.038,
      sideOffsetMultiplier: 1.11,
    },
  },
  silhouetteCurves: {
    bodyTaper: 0.48,
    roofCurve: 1.18,
    roofHeight: 0.08,
    roofBaseRatio: 0.15,
    cabinPeakStart: 0.22,
    cabinPeakExtraLength: 0.15,
    frontTaperStrength: 0.6,
    sourceCurvesMm: {
      hoodTop: [
        { x: xAnchorsMm.frontBumper + 90, z: 700 },
        { x: -560, z: 748 },
        { x: -180, z: 790 },
        { x: 250, z: 842 },
        { x: 600, z: 880 },
      ],
      roofline: [
        { x: 500, z: 890 },
        { x: 850, z: 1248 },
        { x: 1130, z: 1350 },
        { x: 1480, z: 1375 },
        { x: 1900, z: 1340 },
        { x: 2260, z: 1242 },
        { x: 2540, z: 1005 },
      ],
      beltline: [
        { x: 420, z: 890 },
        { x: 950, z: 900 },
        { x: 1480, z: 920 },
        { x: 2050, z: 955 },
        { x: 2500, z: 1005 },
        { x: 3150, z: 990 },
        { x: 3660, z: 935 },
      ],
      rocker: [
        { x: xAnchorsMm.frontBumper + 180, z: 250 },
        { x: 300, z: 270 },
        { x: 1450, z: 280 },
        { x: 2700, z: 280 },
        { x: xAnchorsMm.rearBumper - 120, z: 255 },
      ],
      trunkDeck: [
        { x: 2540, z: 980 },
        { x: 2920, z: 985 },
        { x: 3320, z: 965 },
        { x: xAnchorsMm.rearBumper - 135, z: 875 },
        { x: xAnchorsMm.rearBumper, z: 760 },
      ],
    },
  },
  topViewProfile: {
    noseWidthRatio: 1.62,
    grilleWidthRatio: 1.35,
    rearWidthRatio: 1.62,
    shoulderWidthRatio: 2.02,
    sideSkirtWidthMultiplier: 1.05,
    sourceHalfWidthStationsMm: [
      { x: xAnchorsMm.frontBumper, halfWidth: 760 },
      { x: xAnchorsMm.frontBumper + 220, halfWidth: 805 },
      { x: -100, halfWidth: 850 },
      { x: 600, halfWidth: 875 },
      { x: 1450, halfWidth: 887.5 },
      { x: 2300, halfWidth: 875 },
      { x: xAnchorsMm.rearAxle, halfWidth: 865 },
      { x: xAnchorsMm.rearBumper - 220, halfWidth: 835 },
      { x: xAnchorsMm.rearBumper, halfWidth: 790 },
    ],
    sourceProfile: {
      noseTaperRatio: 0.86,
      tailTaperRatio: 0.89,
      shoulderMaxWidthMm: 1775,
      glasshouseMaxHalfWidthMm: 705,
      cabinTumblehomeMm: 145,
      sideCurvatureIntensity: 0.035,
    },
  },
  pillars: {
    sourcePillarsMm: {
      aPillar: {
        base: { x: 510, y: -650, z: 900 },
        top: { x: 875, y: -575, z: 1395 },
        thicknessMm: 82,
        angleFromVerticalDeg: 29,
        mirrored: true,
      },
      bPillar: {
        base: { x: 1450, y: -690, z: 870 },
        top: { x: 1480, y: -610, z: 1390 },
        thicknessMm: 92,
        color: "black",
        mirrored: true,
      },
      cPillar: {
        base: { x: 2460, y: -680, z: 925 },
        top: { x: 2120, y: -585, z: 1345 },
        thicknessMm: 165,
        angleFromVerticalDeg: 34,
        mirrored: true,
      },
    },
    aPillar: {
      xOffsetFromCabinCenter: -0.12,
      yRatio: 0.52,
      rotationZ: -0.24,
      width: 0.055,
      heightRatio: 0.92,
      depthRatio: 1.54,
    },
    bPillar: {
      xOffsetFromCabinCenter: -0.05,
      yRatio: 0.78,
      width: 0.04,
      heightRatio: 0.66,
    },
    cPillar: {
      xCabinLengthRatio: 0.55,
      yRatio: 0.4784,
      rotationZ: 0.18,
      width: 0.055,
      heightRatio: 0.78,
      depthRatio: 1.42,
    },
  },
  windows: {
    sourceGlasshouseMm: {
      windshield: {
        lowerLeft: { x: 525, y: -625, z: 890 },
        lowerRight: { x: 525, y: 625, z: 890 },
        upperLeft: { x: 930, y: -520, z: 1328 },
        upperRight: { x: 930, y: 520, z: 1328 },
        curvature: 0.08,
        rakeDegFromVertical: 34,
        blackCeramicBorderMm: 35,
      },
      rearGlass: {
        lowerLeft: { x: 2525, y: -600, z: 960 },
        lowerRight: { x: 2525, y: 600, z: 960 },
        upperLeft: { x: 2070, y: -535, z: 1292 },
        upperRight: { x: 2070, y: 535, z: 1292 },
        curvature: 0.07,
        rakeDegFromVertical: 38,
        blackCeramicBorderMm: 32,
      },
      sideWindowsLeft: {
        frontDoorGlass: [
          { x: 540, y: -705, z: 900 },
          { x: 925, y: -630, z: 1300 },
          { x: 1450, y: -635, z: 1315 },
          { x: 1425, y: -710, z: 905 },
        ],
        rearDoorGlass: [
          { x: 1515, y: -710, z: 910 },
          { x: 1565, y: -635, z: 1310 },
          { x: 2080, y: -625, z: 1282 },
          { x: 2400, y: -700, z: 925 },
        ],
        smallQuarterGlassHint: false,
        trimThicknessMm: 12,
      },
      glassTintOpacity: 0.33,
      glassReflectivity: 0.75,
    },
    windshield: {
      xOffsetFromCabinCenter: -0.85,
      yRatio: 0.98,
      rotationZ: 0.12,
      lengthRatio: 0.48,
      height: 0.032,
      widthRatio: 1.22,
    },
    rearGlass: {
      xOffsetFromCabinCenter: 0.65,
      yRatio: 1.05,
      lengthRatio: 0.52,
      height: 0.032,
      widthRatio: 1.42,
    },
    sideFront: {
      xOffsetFromCabinCenter: -0.95,
      yRatio: 0.76,
      lengthRatio: 0.55,
      height: 0.34,
    },
    sideRear: {
      xOffsetFromCabinCenter: 0.55,
      yRatio: 0.78,
      lengthRatio: 0.58,
      height: 0.38,
    },
    quarter: {
      xOffsetFromCabinCenter: -1.65,
      yRatio: 0.72,
      rotationZ: -0.16,
      length: 0.55,
      height: 0.26,
    },
  },
  characterLines: {
    sourceCharacterLinesMm: {
      upperShoulderLeft: {
        curve: [
          { x: 250, y: -890, z: 815 },
          { x: 900, y: -905, z: 870 },
          { x: 1600, y: -908, z: 910 },
          { x: 2350, y: -890, z: 945 },
          { x: 3280, y: -835, z: 900 },
        ],
        depthMm: 18,
        sharpness: 0.62,
      },
      lowerDoorCreaseLeft: {
        curve: [
          { x: 450, y: -895, z: 520 },
          { x: 1150, y: -910, z: 555 },
          { x: 1980, y: -905, z: 590 },
          { x: 2850, y: -875, z: 605 },
        ],
        depthMm: 14,
        sharpness: 0.35,
      },
      rockerShadowLineLeft: {
        curve: [
          { x: -150, y: -885, z: 285 },
          { x: 700, y: -900, z: 285 },
          { x: 1700, y: -900, z: 285 },
          { x: 2850, y: -880, z: 285 },
          { x: 3450, y: -840, z: 285 },
        ],
        depthMm: 22,
        sharpness: 0.35,
      },
    },
    beltline: {
      frontXOffsetFromCabinCenter: -0.85,
      rearXOffsetFromCabinCenter: 0.4,
      yRatio: 0.38,
      thickness: 0.022,
      depth: 0.036,
    },
    rockerLine: {
      yRatio: -0.68,
      lengthRatio: 0.88,
      height: 0.09,
      depth: 0.035,
    },
  },
  hood: {
    sourceHoodMm: {
      xStart: xAnchorsMm.frontBumper + 120,
      xEnd: xAnchorsMm.firewallApprox + 130,
      frontZ: zAnchorsMm.hoodFront,
      rearZ: zAnchorsMm.hoodRear - 20,
      slopeDegApprox: 5.2,
      centerCrownMm: 8,
      sideFalloffMm: 18,
      leadingEdgeRoundnessMm: 45,
      rearPanelGapMm: 4,
    },
    frontPanelXOffsetFromBumper: 0.18,
    grilleXOffsetFromBumper: 0.26,
    lowerIntakeXOffsetFromBumper: 0.30,
    chromeStripXOffsetFromBumper: 0.32,
    hoodSlopeHint: "smooth low compact-sedan hood with a gentle cowl-to-bumper slope",
  },
} as const;


export const corollaSchemaExterior = {
  frontDesign: {
    sourceFrontEndMm: {
      planeX: xAnchorsMm.frontBumper,
      designLanguage: "thin upper grille + compact inset lower intake + rounded front bumper",
      upperGrille: {
        center: { x: xAnchorsMm.frontBumper - 2, y: 0, z: 730 },
        widthMm: 1040,
        heightMm: 54,
        depthMm: 28,
        shape: "thin_horizontal_slight_smile",
        cornerRadiusMm: 18,
        chromeTopBar: true,
        chromeBarHeightMm: 18,
        material: "glossBlack",
      },
      badge: {
        center: { x: xAnchorsMm.frontBumper - 9, y: 0, z: 735 },
        widthMm: 145,
        heightMm: 98,
        depthMm: 14,
        material: "chrome",
      },
      lowerIntake: {
        center: { x: xAnchorsMm.frontBumper + 8, y: 0, z: 505 },
        widthTopMm: 900,
        widthBottomMm: 980,
        heightMm: 150,
        depthMm: 34,
        shape: "compact_inset_horizontal",
        meshPattern: "simple_horizontal_or_honeycomb_low_density",
        material: "matteBlack",
      },
      bumper: {
        upperRoundnessMm: 55,
        lowerRoundnessMm: 80,
        cornerRoundnessMm: 90,
        angularCutIntensity: 0.08,
        lipProtrusionMm: 0,
        lowerLipZ: 300,
      },
      fogLightPods: {
        optional: true,
        centerLeft: { x: xAnchorsMm.frontBumper - 12, y: -640, z: 500 },
        centerRight: { x: xAnchorsMm.frontBumper - 12, y: 640, z: 500 },
        podWidthMm: 250,
        podHeightMm: 170,
        lampDiameterMm: 95,
        bezelMaterial: "blackPlastic",
      },
    },
    bumperFaceHeightRatio: 0.66,
    grilleHeightRatio: 0.5,
    lowerIntakeHeightRatio: 0.32,
    grilleDepthRatio: 1.35,
    lowerIntakeDepthRatio: 1.14,
    chromeStripDepthRatio: 0.54,
  },
  headlights: {
    centerY: 0.68,
    xOffsetFromBumper: 0.34,
    turnSignalXOffsetFromBumper: 0.36,
    mainSize: [0.055, 0.14, 0.52],
    turnSignalSize: [0.04, 0.11, 0.16],
    lateralOffsetRatio: 0.64,
    turnSignalLateralOffsetRatio: 0.96,
    rotationY: 0.18,
    sourceHeadlightsMm: {
      style: "long_narrow_angular_wraparound",
      left: {
        outline: [
          { x: xAnchorsMm.frontBumper - 8, y: -150, z: 790 },
          { x: xAnchorsMm.frontBumper - 5, y: -555, z: 820 },
          { x: xAnchorsMm.frontBumper + 80, y: -790, z: 760 },
          { x: xAnchorsMm.frontBumper + 120, y: -760, z: 690 },
          { x: xAnchorsMm.frontBumper + 20, y: -250, z: 700 },
        ],
        lengthMm: 650,
        heightMm: 155,
        wrapAroundSideMm: 180,
        sweepAngleDeg: 12,
        topEdgeSharpness: 0.75,
        innerCornerSharpness: 0.65,
        outerCornerSharpness: 0.42,
        lensMaterial: "lightLensClear",
        internalReflectorChambers: 3,
        ledDrlStrip: {
          exists: true,
          position: "upper_or_lower_inner_edge",
          thicknessMm: 16,
          colorTemperatureK: 5500,
        },
      },
      rightMirrorOfLeft: true,
    },
  },
  doors: {
    count: 4,
    frontDoorLengthRatio: 0.48,
    rearDoorLengthRatio: 0.52,
    handleYRatio: 0.38,
    bPillarDividesDoors: true,
    sourceDoorsMm: {
      leftFrontDoor: {
        outline: [
          { x: 500, y: -892, z: 300 },
          { x: 520, y: -890, z: 890 },
          { x: 885, y: -700, z: 1350 },
          { x: 1450, y: -704, z: 1370 },
          { x: 1450, y: -895, z: 300 },
        ],
        handleCenter: { x: 1110, y: -905, z: 905 },
        handleLengthMm: 172,
        handleHeightMm: 38,
        handleProtrusionMm: 20,
        seamGapMm: 4,
      },
      leftRearDoor: {
        outline: [
          { x: 1450, y: -895, z: 300 },
          { x: 1455, y: -710, z: 920 },
          { x: 2095, y: -700, z: 1320 },
          { x: 2485, y: -890, z: 920 },
          { x: 2485, y: -875, z: 305 },
        ],
        handleCenter: { x: 2030, y: -900, z: 925 },
        handleLengthMm: 165,
        handleHeightMm: 38,
        handleProtrusionMm: 20,
        seamGapMm: 4,
      },
      rightMirrorOfLeft: true,
    },
  },
  mirrors: {
    style: "small-body-colored-side-mirrors",
    xOffsetFromCabinCenter: -1.15,
    yRatio: 0.68,
    lateralOffsetMultiplier: 1.2,
    size: [0.12, 0.07, 0.22],
    sourceExteriorPartsMm: {
      leftMirror: {
        mountCenter: { x: 620, y: -890, z: 1020 },
        housingCenter: { x: 610, y: -1020, z: 1040 },
        widthMm: 235,
        heightMm: 120,
        depthMm: 145,
        shape: "rounded_aerodynamic_teardrop",
        bodyColorCap: true,
        blackPlasticBase: true,
        turnSignalIntegrated: false,
      },
      wipers: {
        leftBladeLengthMm: 650,
        rightBladeLengthMm: 400,
        pivotLeft: { x: 520, y: -230, z: 910 },
        pivotRight: { x: 520, y: 230, z: 910 },
        restingAngleDeg: 8,
        material: "blackPlastic",
      },
      antenna: {
        type: "short_roof_mast_or_rear_roof_antenna",
        base: { x: 2350, y: 0, z: 1440 },
        heightMm: 90,
        material: "blackPlastic",
      },
    },
  },
  rearDesign: {
    deckHint: "short rear deck with vertical tail face",
    bumperXOffsetFromRearBumper: -0.16,
    bumperY: -0.14,
    bumperSize: [0.07, 0.26],
    sourceRearEndMm: {
      planeX: xAnchorsMm.rearBumper,
      designLanguage: "clean horizontal rear with large angular lamps and defined trunk lid",
      trunkLid: {
        panelOutline: [
          { x: xAnchorsMm.rearBumper - 55, y: -650, z: 615 },
          { x: xAnchorsMm.rearBumper - 75, y: -620, z: 940 },
          { x: 2920, y: -650, z: 1025 },
          { x: 2920, y: 650, z: 1025 },
          { x: xAnchorsMm.rearBumper - 75, y: 620, z: 940 },
          { x: xAnchorsMm.rearBumper - 55, y: 650, z: 615 },
        ],
        licensePlateRecess: {
          center: { x: xAnchorsMm.rearBumper - 42, y: 0, z: 690 },
          widthMm: 530,
          heightMm: 175,
          depthMm: 20,
          cornerRadiusMm: 10,
        },
        badgeCenter: { x: xAnchorsMm.rearBumper - 35, y: 0, z: 855 },
      },
      bumper: {
        heightMm: 520,
        roundnessMm: 90,
        lowerTuckMm: 70,
        diffuser: false,
        visibleExhaust: "minimal_or_hidden",
        reflectorOptional: true,
        lowerEdgeZ: 310,
      },
    },
  },
  taillights: {
    centerY: 0.62,
    xOffsetFromRearBumper: -0.14,
    lateralOffsetRatio: 0.62,
    size: [0.055, 0.22, 0.32],
    emissiveColor: "#7f1d1d",
    sourceTaillightsMm: {
      style: "wide_horizontal_angular_boomerang_wraparound",
      left: {
        outline: [
          { x: xAnchorsMm.rearBumper - 36, y: -150, z: 825 },
          { x: xAnchorsMm.rearBumper - 42, y: -520, z: 842 },
          { x: xAnchorsMm.rearBumper - 70, y: -760, z: 790 },
          { x: xAnchorsMm.rearBumper - 92, y: -748, z: 704 },
          { x: xAnchorsMm.rearBumper - 44, y: -185, z: 708 },
        ],
        widthMm: 610,
        heightMm: 150,
        wrapAroundSideMm: 130,
        redLensRatio: 0.72,
        clearLensRatio: 0.2,
        amberLensRatio: 0.08,
        topEdgeSharpness: 0.55,
        innerEdgeSharpness: 0.3,
      },
      rightMirrorOfLeft: true,
    },
  },
  wheels: {
    tireColor: "#050505",
    rimColor: "#cbd5e1",
    sportRimColor: "#e5e7eb",
    spokeColor: "#94a3b8",
    sportSpokeColor: "#f8fafc",
    centerCapColor: "#f8fafc",
    sourceWheelDesigns: {
      steel15WithCover: {
        label: "15 inch steel wheel with cover",
        tireKey: "tire19565R15",
        rimDiameterIn: 15,
        rimWidthIn: 6,
        coverSpokes: 8,
        spokeStyle: "broad_plastic_cover_spokes",
        lugCount: 5,
        centerCapDiameterMm: 92,
        materialMain: "interiorPlasticGray",
      },
      alloy16Simple: {
        label: "16 inch simple alloy",
        tireKey: "tire20555R16",
        rimDiameterIn: 16,
        rimWidthIn: 6.5,
        spokes: 10,
        spokeStyle: "simple_split_or_slim_spokes",
        lugCount: 5,
        centerCapDiameterMm: 86,
        materialMain: "chrome",
      },
      sport17Black: {
        label: "17 inch gloss black sport alloy",
        tireKey: "tire21545R17",
        rimDiameterIn: 17,
        rimWidthIn: 7,
        spokes: 12,
        spokeStyle: "angular_sport_spokes",
        lugCount: 5,
        centerCapDiameterMm: 86,
        materialMain: "glossBlack",
      },
    },
  },
  materials: {
    body: { roughness: 0.32, metalness: 0.19 },
    cabinBody: { roughness: 0.28, metalness: 0.13 },
    blackTrim: { color: "#0f172a", roughness: 0.28, metalness: 0.11 },
    glass: { color: "#12303a", roughness: 0.08, metalness: 0.11 },
    chrome: { color: "#d1d5db", roughness: 0.16, metalness: 0.52 },
    lowerTrim: { color: "#111827", roughness: 0.4 },
    sourceMaterials: {
      bodyPaint: {
        shader: "principled_clearcoat",
        baseColor: "#F8F8F2",
        metallic: 0.25,
        roughness: 0.18,
        clearcoat: 1.0,
        clearcoatRoughness: 0.08,
        normalIntensity: 0.02,
      },
      blackPlastic: {
        shader: "principled",
        baseColor: "#111111",
        metallic: 0.0,
        roughness: 0.55,
      },
      glossBlack: {
        shader: "principled",
        baseColor: "#050505",
        metallic: 0.0,
        roughness: 0.16,
        clearcoat: 0.6,
      },
      matteBlack: {
        shader: "principled",
        baseColor: "#070707",
        metallic: 0.0,
        roughness: 0.68,
      },
      chrome: {
        shader: "metallic",
        baseColor: "#D8D8D8",
        metallic: 1.0,
        roughness: 0.14,
      },
      glass: {
        shader: "physical_transmission",
        baseColor: "#1C2730",
        transmission: 0.36,
        opacity: 0.48,
        roughness: 0.02,
        reflectivity: 0.78,
        ior: 1.45,
      },
      tireRubber: {
        shader: "principled",
        baseColor: "#070707",
        metallic: 0.0,
        roughness: 0.78,
        sidewallBumpIntensity: 0.16,
      },
      lightLensClear: {
        shader: "physical_transparent",
        baseColor: "#EAF2FF",
        transmission: 0.62,
        opacity: 0.5,
        roughness: 0.04,
        reflectivity: 0.82,
      },
      lightLensRed: {
        shader: "physical_transparent",
        baseColor: "#B0000F",
        transmission: 0.35,
        opacity: 0.78,
        roughness: 0.08,
      },
      lightLensAmber: {
        shader: "physical_transparent",
        baseColor: "#FF9A00",
        transmission: 0.36,
        opacity: 0.72,
        roughness: 0.08,
      },
      interiorFabricDark: {
        shader: "fabric",
        baseColor: "#272727",
        roughness: 0.86,
        weaveIntensity: 0.18,
      },
      interiorPlasticDark: {
        shader: "principled",
        baseColor: "#171717",
        roughness: 0.64,
      },
      interiorPlasticGray: {
        shader: "principled",
        baseColor: "#6D6D6D",
        roughness: 0.58,
      },
    },
  },
  colors: {
    defaultPaint: "white",
    recommendedPaints: ["white", "graphite", "red", "blue"],
    factoryReference: "white compact sedan rental trim",
    sourceExteriorPaintColors: {
      superWhite: { name: "Super White", hex: "#F8F8F2", metallic: 0.02 },
      classicSilverMetallic: { name: "Classic Silver Metallic", hex: "#BFC2C4", metallic: 0.48 },
      slateMetallic: { name: "Slate Metallic", hex: "#4A4D50", metallic: 0.42 },
      blackSandPearl: { name: "Black Sand Pearl", hex: "#050505", metallic: 0.35 },
      barcelonaRedMetallic: { name: "Barcelona Red Metallic", hex: "#8C1D18", metallic: 0.42 },
      blueCrushMetallic: { name: "Blue Crush Metallic", hex: "#1C4F8F", metallic: 0.45 },
      brownSugarMetallic: { name: "Brown Sugar Metallic", hex: "#8A6E56", metallic: 0.38 },
      absolutelyRed: { name: "Absolutely Red", hex: "#B5121B", metallic: 0.18 },
    },
  },
} as const;


export const corollaSchemaInterior = {
  interiorVisible: {
    seats: "suggested-through-dark-glass",
    dashboard: {
      shape: "horizontal_layered_rectangular",
      widthMm: 1460,
      depthMm: 520,
      topZ: 940,
      frontX: 640,
      centerStack: {
        center: { x: 760, y: 0, z: 835 },
        widthMm: 360,
        heightMm: 430,
        screenWidthMm: 180,
        screenHeightMm: 105,
        climateControls: "three_knobs_or_auto_panel_by_trim",
      },
      passengerShelfLine: {
        z: 840,
        horizontalEmphasis: true,
      },
    },
    steeringWheel: {
      side: "left_hand_drive",
      center: { x: 760, y: -430, z: 900 },
      diameterMm: 370,
      rimThicknessMm: 34,
      spokes: 3,
      columnAngleDeg: 22,
    },
    sourceSeatsMm: {
      frontLeft: { center: { x: 1120, y: -380, z: 500 }, widthMm: 500, depthMm: 540, backHeightMm: 760 },
      frontRight: { center: { x: 1120, y: 380, z: 500 }, widthMm: 500, depthMm: 540, backHeightMm: 760 },
      rearBench: { center: { x: 2050, y: 0, z: 480 }, widthMm: 1320, depthMm: 520, backHeightMm: 700 },
      upholstery: "gray_or_black_cloth",
    },
    centerConsole: {
      xStart: 880,
      xEnd: 1600,
      yHalfWidth: 145,
      zTop: 520,
      gearSelector: { center: { x: 1030, y: 0, z: 555 }, type: "automatic_or_cvt_shifter" },
      cupholders: [{ x: 1270, y: 0, z: 545, radiusMm: 42 }],
      handbrake: { visible: true, sideOffsetY: -80, lengthMm: 260 },
    },
    glassOpacityHint: 1,
  },
  panelDetails: {
    panelGaps: {
      defaultGapMm: 4,
      bumperGapMm: 5,
      hoodGapMm: 4,
      trunkGapMm: 4,
      fuelDoorGapMm: 3,
      edgeBevelMm: 2.5,
      panelInsetDepthMm: 2.5,
      weatherStripColorHex: "#050505",
    },
    licensePlate: {
      rearRecess: {
        center: { x: xAnchorsMm.rearBumper - 42, y: 0, z: 690 },
        widthMm: 530,
        heightMm: 175,
        depthMm: 20,
        cornerRadiusMm: 10,
      },
    },
    fuelDoorSide: "left-rear",
    badges: ["Toyota", "Corolla"],
    trimLevel: "rental-friendly-base",
    trimProfiles: {
      L: {
        wheel: "15in_steel_cover",
        lowerBumperSportiness: 0.1,
        spoiler: false,
        fogLights: false,
        grilleChromeIntensity: 0.35,
        stanceVisualLoweringMm: 0,
      },
      LE: {
        wheel: "16in_simple_alloy",
        lowerBumperSportiness: 0.18,
        spoiler: false,
        fogLights: false,
        grilleChromeIntensity: 0.45,
        stanceVisualLoweringMm: 0,
      },
      S: {
        wheel: "16_or_17in_sport_alloy",
        lowerBumperSportiness: 0.42,
        spoiler: true,
        fogLights: true,
        grilleChromeIntensity: 0.55,
        stanceVisualLoweringMm: 8,
      },
      SPECIAL_EDITION: {
        wheel: "17in_black_alloy",
        lowerBumperSportiness: 0.48,
        spoiler: true,
        fogLights: true,
        grilleChromeIntensity: 0.55,
        stanceVisualLoweringMm: 10,
        redInteriorAccents: true,
      },
    },
  },
  semanticRules: {
    keepCabinCenteredBetweenAxles: true,
    preserveFourDoorSedanRead: true,
    avoidFastbackRoofline: true,
    roofShouldStayLowAndPractical: true,
    frontOverhangMustBeShorterThanRearOrEqual: true,
    wheelsMustAlignToWheelbase: true,
    identityMustHave: [
      "compact four-door sedan",
      "three-box profile: hood, cabin, trunk",
      "Toyota Corolla 2016 E170/E180 inspired proportions",
      "thin upper grille",
      "wide lower front intake",
      "angular horizontal headlights",
      "headlights extend into front fenders",
      "rising side beltline",
      "large rear passenger door",
      "thick C-pillar",
      "defined trunk deck",
      "large horizontal angular taillights",
      "clean rounded wheel arches",
      "moderate urban ride height",
      "15 or 16 inch normal wheels for standard trim",
    ],
    avoid: [
      "SUV stance",
      "hatchback rear",
      "coupe two-door roofline",
      "supercar low ground clearance",
      "widebody fenders",
      "oversized rear wing",
      "large visible sport exhaust",
      "round headlights",
      "vertical headlights",
      "box truck silhouette",
      "extreme fastback roof",
      "aggressive racing diffuser",
    ],
    styleAdjectives: [
      "practical",
      "clean",
      "modern",
      "horizontal",
      "slightly angular",
      "not extreme",
      "family sedan",
      "urban compact",
    ],
    validationTargets: {
      lengthWidthRatioMin: 2.45,
      lengthWidthRatioMax: 2.75,
      lengthHeightRatioMin: 3.0,
      lengthHeightRatioMax: 3.35,
      wheelbaseLengthRatioMin: 0.56,
      wheelbaseLengthRatioMax: 0.60,
      lengthWidthRatioTarget: sourceDerived.lengthToWidthRatio,
      wheelbaseLengthRatioTarget: sourceDerived.wheelbaseToLengthRatio,
      cabinShouldBeVisuallySpacious: true,
      trunkMustBeClearlySeparated: true,
    },
    designChecklist: {
      global: [
        "Use 4-door sedan, not hatchback.",
        "Use three-box silhouette with clear trunk.",
        "Keep roof arc smooth, not coupe-fastback.",
        "Use moderate ground clearance, not slammed stance.",
      ],
      front: [
        "Thin upper grille between headlights.",
        "Large wide lower intake in bumper.",
        "Angular horizontal headlights extending to fenders.",
        "Centered badge on upper grille.",
      ],
      side: [
        "Rising beltline from front to rear.",
        "Large rear door and thick C-pillar.",
        "Clean rounded wheel arches.",
        "Subtle lower door crease.",
      ],
      rear: [
        "Horizontal angular taillights wrapping into sides.",
        "Trunk lid high and defined.",
        "Rear bumper clean and rounded.",
        "No large diffuser or large exposed exhaust.",
      ],
      materials: [
        "Automotive clearcoat paint.",
        "Slightly tinted reflective glass.",
        "Black plastic lower intake and mirror bases.",
        "Chrome badges and subtle trim.",
      ],
    },
  },
} as const;

