import {
  Clock,
  Compass,
  Droplets,
  MessageCircle,
  Percent,
  Star,
  Sun,
  TreePine,
  Users,
  Waves,
} from "lucide-react";
import type { Flyer, FlyerAccent } from "./types";

/**
 * Paleta oficial de la logoguía (turquesa + negro cálido) y sus tintes
 * derivados. Sin colores de señalización vial: ver
 * `.agents/skills/la-vieja-brand-design/references/brand-system.md`.
 */
const TURQUOISE: FlyerAccent = { bg: "#00C4B0", text: "#062824", wash: "rgba(0,196,176,0.4)" };
const DEEP_TEAL: FlyerAccent = { bg: "#0A6F63", text: "#FFFFFF", wash: "rgba(10,111,99,0.45)" };
const WARM_BLACK: FlyerAccent = { bg: "#2E2A25", text: "#FFFFFF", wash: "rgba(46,42,37,0.55)" };
const MIST: FlyerAccent = { bg: "#F3FBF9", text: "#12302B" };
const AMBER: FlyerAccent = { bg: "#F3A712", text: "#2E2A25", wash: "rgba(243,167,18,0.32)" };

/**
 * Diez publicaciones listas para Instagram, todas en formato cuadrado
 * 1080 × 1080. Comparten fotografía, marca y editor con los rótulos, pero el
 * mensaje de cada una está pensado para redes sociales, no para carretera.
 */
export const FLYERS: Flyer[] = [
  {
    id: 1,
    code: "IG-01",
    layoutId: "flyer-bienvenida",
    icon: Compass,
    accent: TURQUOISE,
    kicker: "Bienvenidos · Welcome",
    title: "Cañón del Río La Vieja",
    titleEn: "Adventure Canyon, Costa Rica",
    subtitle: "Sucre, San Carlos · A 3 horas de San José",
    cta: { es: "Vivilo hoy", en: "Live it today" },
    photo: "/image/IMG_4946.JPG",
  },
  {
    id: 2,
    code: "IG-02",
    layoutId: "flyer-canyoning",
    icon: Waves,
    accent: WARM_BLACK,
    kicker: "Tour de aventura",
    title: "Canyoning Extremo",
    titleEn: "Extreme Canyoning Tour",
    subtitle: "Rappel, pozas naturales y guías certificados",
    cta: { es: "Reservá tu cupo", en: "Book your spot" },
    photo: "/image/IMG_3705.jpg",
    weatherDependent: true,
  },
  {
    id: 3,
    code: "IG-03",
    layoutId: "flyer-cascadas",
    icon: Droplets,
    accent: TURQUOISE,
    kicker: "Cascadas escondidas",
    title: "Persigue la Cascada",
    titleEn: "Chase the Waterfall",
    subtitle: "Senderos guiados hacia caídas de agua únicas",
    cta: { es: "Explorá ya", en: "Explore now" },
    photo: "/image/IMG_5038.JPG",
    weatherDependent: true,
  },
  {
    id: 4,
    code: "IG-04",
    layoutId: "flyer-grupo",
    icon: Users,
    accent: MIST,
    kicker: "Aventura en grupo",
    title: "Traé a tu Gente",
    titleEn: "Bring Your Crew",
    subtitle: "Tours para familia, amigos y grupos corporativos",
    cta: { es: "Cotizá tu grupo", en: "Get a group quote" },
    photo: "/image/IMG_2986.jpg",
  },
  {
    id: 5,
    code: "IG-05",
    layoutId: "flyer-senderos",
    icon: TreePine,
    accent: DEEP_TEAL,
    kicker: "Senderos y rappel",
    title: "Subí, Bajá, Explorá",
    titleEn: "Climb, Descend, Explore",
    subtitle: "Rutas guiadas para todos los niveles de experiencia",
    cta: { es: "Elegí tu ruta", en: "Choose your route" },
    photo: "/image/IMG_3920.jpg",
    weatherDependent: true,
  },
  {
    id: 6,
    code: "IG-06",
    layoutId: "flyer-luz",
    icon: Sun,
    accent: MIST,
    kicker: "Momento mágico",
    title: "Donde Entra la Luz",
    titleEn: "Where the Light Breaks In",
    subtitle: "El rayo de sol que todos quieren fotografiar",
    cta: { es: "Guardá la fecha", en: "Save the date" },
    photo: "/image/IMG_11447.jpg",
  },
  {
    id: 7,
    code: "IG-07",
    layoutId: "flyer-promo",
    icon: Percent,
    accent: AMBER,
    kicker: "Promo de temporada",
    title: "2x1 Entre Semana",
    titleEn: "2-for-1, Weekdays",
    subtitle: "Lunes a jueves, cupos limitados",
    cta: { es: "Aprovechá ya", en: "Grab it now" },
    photo: "/image/IMG_4200.jpg",
  },
  {
    id: 8,
    code: "IG-08",
    layoutId: "flyer-horario",
    icon: Clock,
    accent: WARM_BLACK,
    kicker: "Horario y ubicación",
    title: "Abrimos Todos los Días",
    titleEn: "Open Every Day",
    subtitle: "8:00 a.m. – 4:00 p.m. · Sucre, San Carlos",
    cta: { es: "Planificá tu visita", en: "Plan your visit" },
    photo: "/image/IMG_4671.jpg",
  },
  {
    id: 9,
    code: "IG-09",
    layoutId: "flyer-resenas",
    icon: Star,
    accent: TURQUOISE,
    kicker: "Lo que dicen de nosotros",
    title: "5 Estrellas en Aventura",
    titleEn: "5-Star Adventure",
    subtitle: "Reseñas reales de visitantes felices",
    cta: { es: "Sumate a la lista", en: "Join the list" },
    photo: "/image/IMG_6805.jpg",
  },
  {
    id: 10,
    code: "IG-10",
    layoutId: "flyer-reserva",
    icon: MessageCircle,
    accent: TURQUOISE,
    kicker: "Reservá tu cupo",
    title: "Tu Aventura te Espera",
    titleEn: "Your Adventure Awaits",
    subtitle: "Escribinos por WhatsApp o escaneá el QR",
    cta: { es: "Reservar ahora", en: "Book now" },
    photo: "/image/IMG_3505.jpg",
    showQr: true,
  },
];
