export const S = {
  root: {
    minHeight: "100vh",
    background: "#060c10",
    color: "#e0e0e0",
    fontFamily: '"Courier New", monospace',
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    padding: "24px 16px",
  },
  card: {
    background: "#0d1a12",
    border: "1px solid #1a3a20",
    borderRadius: 12,
    padding: "32px 28px",
    maxWidth: 480,
    width: "100%",
    boxShadow: "0 0 40px rgba(0,230,118,0.08)",
  },
  title: {
    fontSize: 22,
    fontWeight: 700,
    color: "#00e676",
    marginBottom: 6,
    textShadow: "0 0 16px rgba(0,230,118,0.6)",
    textAlign: "center" as const,
  },
  subtitle: {
    fontSize: 12,
    color: "#4caf50",
    marginBottom: 28,
    textAlign: "center" as const,
    letterSpacing: 2,
  },
  label: { fontSize: 11, color: "#4caf50", letterSpacing: 1.5, marginBottom: 6 },
  input: {
    width: "100%",
    background: "#111d14",
    border: "1px solid #2a4a2e",
    borderRadius: 8,
    padding: "10px 14px",
    color: "#e0e0e0",
    fontFamily: '"Courier New", monospace',
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box" as const,
    marginBottom: 16,
  },
  btn: (primary = true) => ({
    width: "100%",
    padding: "12px 0",
    borderRadius: 8,
    border: "none",
    background: primary ? "#00e676" : "#1a3a20",
    color: primary ? "#060c10" : "#00e676",
    fontFamily: '"Courier New", monospace',
    fontWeight: 700,
    fontSize: 13,
    letterSpacing: 1,
    cursor: "pointer",
    marginBottom: 10,
    transition: "opacity 0.15s",
  }),
  divider: {
    display: "flex" as const,
    alignItems: "center",
    gap: 10,
    margin: "16px 0",
  },
  dividerLine: { flex: 1, height: 1, background: "#1a3a20" },
  dividerText: { fontSize: 11, color: "#2a5a30", letterSpacing: 1 },
  codeBox: {
    background: "#111d14",
    border: "2px solid #00e676",
    borderRadius: 10,
    padding: "18px 20px",
    marginBottom: 24,
    textAlign: "center" as const,
  },
  codeNum: {
    fontSize: 38,
    fontWeight: 900,
    color: "#00e676",
    letterSpacing: 10,
    textShadow: "0 0 20px rgba(0,230,118,0.8)",
    fontVariantNumeric: "tabular-nums",
  },
  codeHint: { fontSize: 11, color: "#4caf50", marginTop: 6, letterSpacing: 1 },
  playerRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 0",
    borderBottom: "1px solid #1a3a20",
  },
  playerDot: (color: string) => ({
    width: 10,
    height: 10,
    borderRadius: "50%",
    background: color,
    flexShrink: 0,
    boxShadow: `0 0 6px ${color}`,
  }),
  badge: (ok: boolean) => ({
    marginLeft: "auto",
    fontSize: 10,
    letterSpacing: 1,
    padding: "2px 8px",
    borderRadius: 4,
    background: ok ? "#1b3a1f" : "#1a1a1a",
    color: ok ? "#00e676" : "#555",
    border: `1px solid ${ok ? "#2a5a2e" : "#333"}`,
  }),
  raceOverlay: {
    position: "fixed" as const,
    top: 0, left: 0, right: 0, bottom: 0,
    pointerEvents: "none" as const,
    zIndex: 20,
  },
  racePanel: {
    position: "absolute" as const,
    top: 16, right: 16,
    background: "rgba(6,12,16,0.88)",
    border: "1px solid #1a3a20",
    borderRadius: 10,
    padding: "14px 16px",
    minWidth: 180,
    pointerEvents: "auto" as const,
    backdropFilter: "blur(6px)",
  },
  raceTitle: {
    fontSize: 10,
    color: "#4caf50",
    letterSpacing: 2,
    marginBottom: 10,
    textAlign: "center" as const,
  },
  progressBar: (pct: number, color: string) => ({
    height: 6,
    borderRadius: 3,
    background: "#1a3a20",
    overflow: "hidden" as const,
    marginTop: 4,
    marginBottom: 8,
  }),
  progressFill: (pct: number, color: string) => ({
    height: "100%",
    width: `${pct}%`,
    background: color,
    borderRadius: 3,
    boxShadow: `0 0 6px ${color}`,
    transition: "width 0.4s ease",
  }),
  error: { color: "#ef5350", fontSize: 12, marginBottom: 12, textAlign: "center" as const },
  hint: { color: "#4caf50", fontSize: 11, textAlign: "center" as const, marginTop: 8, letterSpacing: 0.5 },
};
